Add py as dependency
This dependency was implicitely set through pytest. With [1] the
dependency was removed from pytest, so pytest-html fails with:

ModuleNotFoundError: No module named 'py.xml'; 'py' is not a package

Specify it explicitely as dependency to fix the issue.

[1] https://github.com/pytest-dev/pytest/commit/19dda7c9bdc8ef71c792e0f77a9595bfad8d9248

Signed-off-by: Erik Bloß <erik.bloss@smartmicro.de>